services:
  pgvector:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=langchain
      - POSTGRES_PASSWORD=langchain
      - POSTGRES_DB=langchain
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langchain"]
      interval: 5s
      timeout: 5s
      retries: 5

  langgraph:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql+psycopg://langchain:langchain@pgvector:5432/langchain
      - DATABASE_URI=postgresql://langchain:langchain@pgvector:5432/langchain
      - REDIS_URI=None
      - PYTHONPATH=/app:/app/src
    depends_on:
      pgvector:
        condition: service_healthy
    ports:
      - "127.0.0.1:2024:2024"
    volumes:
      - .:/app
    command: langgraph dev --allow-blocking

volumes:
  pgvector-data: